export const positions = {
    'top left': {
        'left': '0px',
        'top': '80px',
        'position': 'fixed',
        'display': 'flex',
        'justifyContent': 'center',
        'alignItems': 'flex-start',
        'flexDirection': 'column',
        'width': '100%',
        'pointerEvents':
        'none',
        'zIndex': '100',
        'maxWidth': '600px'
    },
    'top center': {
        'left': '50%',
        'top': '80px',
        'transform': 'translateX(-50%)',
        'position': 'fixed',
        'display': 'flex',
        'justifyContent': 'center',
        'alignItems': 'center',
        'flexDirection': 'column',
        'width': '100%',
        'pointerEvents': 'none',
        'zIndex': '100',
        'maxWidth': '600px'
    },
    'top right': {
        'top': '80px',
        'right': '20px',
        'position': 'fixed',
        'display': 'flex',
        'justifyContent': 'center',
        'alignItems': 'flex-end',
        'flexDirection': 'column',
        'width': '100%',
        'pointerEvents': 'none',
        'zIndex': '100',
        'maxWidth': '600px'
    },
    'middle left': {
        'left': '0px',
        'position': 'fixed',
        'display': 'flex',
        'justifyContent': 'center',
        'alignItems': 'flex-start',
        'flexDirection': 'column',
        'width': '100%',
        'pointerEvents': 'none',
        'top': '50%',
        'zIndex': '100',
        'maxWidth': '600px'
    },
    'middle': {
        'left': '50%',
        'transform': 'translateX(-50%)',
        'top': '50%',
        'position': 'fixed',
        'display': 'flex',
        'justifyContent': 'center',
        'alignItems': 'center',
        'flexDirection': 'column',
        'width': '100%',
        'pointerEvents': 'none',
        'zIndex': '100',
        'maxWidth': '600px'
    },
    'middle right': {
        'right': '20px',
        'top': '50%',
        'transform': 'translateY(-50%)',
        'position': 'fixed',
        'display': 'flex',
        'justifyContent': 'center',
        'alignItems': 'flex-end',
        'flexDirection': 'column',
        'width': '100%',
        'pointerEvents': 'none',
        'zIndex': '100',
        'maxWidth': '600px'
    },
    'bottom left': {
        'left': '20px',
        'bottom': '20px',
        'position': 'fixed',
        'display': 'flex',
        'justifyContent': 'center',
        'alignItems': 'flex-start',
        'flexDirection': 'column',
        'width': '100%',
        'pointerEvents': 'none',
        'zIndex': '100',
        'maxWidth': '600px'
    },
    'bottom center': {

        'left': '50%',
        'transform': 'translateX(-50%)',
        'position': 'fixed',
        'display': 'flex',
        'justifyContent': 'center',
        'alignItems': 'center',
        'flexDirection': 'column',
        'width': '100%',
        'pointerEvents': 'none',
        'bottom': '20px',
        'zIndex': '100',
        'maxWidth': '600px'
    },
    'bottom right': {
        'right': '20px',
        'bottom': '20px',
        'position': 'fixed',
        'display': 'flex',
        'justifyContent': 'center',
        'alignItems': 'flex-end',
        'flexDirection': 'column',
        'width': '100%',
        'pointerEvents': 'none',
        'zIndex': '100',
        'maxWidth': '600px'
    }
}